[build-system]
requires = [
    "setuptools",
    "cmake>=3.20",
    "pybind11",
    "wheel",
    "ninja; sys_platform != 'win32' and platform_machine != 'arm64'",
]
build-backend = "setuptools.build_meta"